name: Enterprise DevSecOps CICD Pipeline
on: 
  push:
    branches:
      - QA
    paths:
      - client/**
      - server/**
      - .github/workflows/qa-cicd.yml

jobs:
  gitleaks-scan: #job id / kind of discription / this can be used /called in other piece of pipeline code
    name: Gitleaks Scan # just label name for our jib
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Run Gitleaks Scan
        run:  |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            zricethezav/gitleaks:latest detect \
            --source=/repo \
            --report-format=json \
            --report-path=/repo/gitleaks-report.json \
            --redact \
            --exit-code 0

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: warn

  checkov-terraform:
   name: Checkov Terraform Scan
   runs-on: ubuntu-latest
   needs: gitleaks-scan
   steps:
     - name: Checkout source code
       uses: actions/checkout@v4
     - name: Seutp Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"
     - name: Install checkov
       run: pip install checkov
     - name: Run Checkov Terraform Scan
       run:  |
         checkov -d . \
           --framework terraform \
           --output json > checkov-terraform.json || true
     - name: Upload checkov Terraform Report
       uses: actions/upload-artifact@v4
       with:
         name: checkov-terraform-report
         path: checkov-terraform.json
         if-no-files-found: warn



  checkov-k8s:
   name: Checkov Kubernetes Scan
   runs-on: ubuntu-latest
   needs: gitleaks-scan
   steps:
     - name: Checkout source code
       uses: actions/checkout@v4
     - name: Seutp Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"
     - name: Install checkov
       run: pip install checkov
     - name: Run Checkov Kubernetes Scan
       run:  |
         checkov -d . \
           --framework kubernetes \
           --output json > checkov-k8s.json || true
     - name: Upload checkov Kubernetes Report
       uses: actions/upload-artifact@v4
       with:
         name: checkov-k8s-report
         path: checkov-k8s.json
         if-no-files-found: warn


  checkov-dockerfile:
   name: Checkov Dockerfile Scan
   runs-on: ubuntu-latest
   needs: gitleaks-scan
   steps:
     - name: Checkout source code
       uses: actions/checkout@v4
     - name: Seutp Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"
     - name: Install checkov
       run: pip install checkov
     - name: Run Checkov Dockerfile Scan
       run:  |
         checkov -d . \
           --framework dockerfile \
           --output json > checkov-dockerfile.json || true
     - name: Upload checkov dockerfile Report
       uses: actions/upload-artifact@v4
       with:
         name: checkov-dockerfile-report
         path: checkov-dockerfile.json
         if-no-files-found: warn


  client-trivy-fs:
    name: Client Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: latest
          cache: true

      - name: Verify Trivy Installation
        run:  |
          trivy --version
          which trivy

      - name: Run Trivy FS Scan On Client ( JSON )
        run:  |
          trivy fs ./client \
            --format json \
            --output client-trivy-fs-report.json \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0

      - name: Rub Trivy FS Scan On Client ( Table )
        run:  | 
          trivy fs ./client \
            --format json \
            --severity HIGH,CRITICAL
            --ignore-unfixed \
            --exit-code 0 > client-trivy-fs-report.txt

      - name: Upload Client Trivy JSON Format
        uses: actions/upload-artifact@v4
        with:
          name: client-trivy-fs-json-report
          path: client-trivy-fs-report.json
          if-no-files-found: warn

      - name: Upload Client Trivy Table Report
        uses: actions/upload-artifact@v4
        with:
          name: client-trivy-fs-table-report
          path: client-trivy-fs-report.txt
          if-no-files-found: warn



  server-trivy-fs:
    name: Server Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: latest
          cache: true

      - name: Verify Trivy Installation
        run:  |
          trivy --version
          which trivy

      - name: Run Trivy FS Scan On Server ( JSON )
        run:  |
          trivy fs ./server \
            --format json \
            --output server-trivy-fs-report.json \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0

      - name: Run Trivy FS Scan On Server ( Table )
        run:  | 
          trivy fs ./server \
            --format json \
            --severity HIGH,CRITICAL
            --ignore-unfixed \
            --exit-code 0 > server-trivy-fs-report.txt

      - name: Upload Server Trivy JSON Format
        uses: actions/upload-artifact@v4
        with:
          name: server-trivy-fs-json-report
          path: server-trivy-fs-report.json
          if-no-files-found: warn

      - name: Upload Server Trivy Table Report
        uses: actions/upload-artifact@v4
        with:
          name: server-trivy-fs-table-report
          path: server-trivy-fs-report.txt
          if-no-files-found: warn
